const GET_COUNTRIES = "GET_COUNTRIES";
const GET_COUNTRIES_BY_ID = "GET_COUNTRIES_BY_ID";
const GET_COUNTRIES_BY_NAME = "GET_COUNTRIES_BY_NAME";
const CREATE_ACTIVITIES = "CREATE_ACTIVITIES";
const ORDER_BY_CONTINENTS = "ORDER_BY_CONTINENTS";
const ORDER_BY_NAME = "ORDER_BY_NAME";
const GET_ACTIVITY = "GET_ACTIVITY";
const GET_FROM = "GET_FROM";
const CLEAN_API = "CLEAN_API";
const CLEAN_BDD = "CLEAN_BDD";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export {
  GET_ACTIVITY,
  GET_COUNTRIES,
  GET_COUNTRIES_BY_ID,
  GET_COUNTRIES_BY_NAME,
  GET_FROM,
  CREATE_ACTIVITIES,
  ORDER_BY_CONTINENTS,
  ORDER_BY_NAME,
  CLEAN_API,
  CLEAN_BDD,
  SET_CURRENT_PAGE,
};
